### PR TITLE
[prometheus-thanos] updated thanos to 0.11.0, enabled compact persistence by default...

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <andre.bauer@kiwigrid.com>

#### What this PR does / why we need it:
* updated thanos to 0.11.0
* enabled compactor persistence by default
* raised default compactor pvc size to 10gb
* moved components manifests in templates subdirs

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://developercertificate.org) signed
- [x] Chart Version bumped (if the pr is an update to an existing chart)
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)

### CODE REVIEW

**Comment by sshishov** [comment]
Guys, you forgot to update your README, and now it does not match completely. I was using existingClaim method and now it is not even in the code, but in README it is stated, that it can be specified.

**Comment by monotek** [comment]
This was not touched by this pr?

**Comment by sshishov** [comment]
@monotek I meant that you have added this to README:
```
The compactor persistence is now enabled by default and the default PVC size was raised to 10GB.
```
But you forgot to change default values in the values table. Therefore it is confusing. Like persistence is still disabled and size is 2GB according to the table.

About existingClaim, I just noticed this inconsistence as well as I tried to use it without any luck.

**Comment by monotek** [comment]
Looks good to me:
https://github.com/kiwigrid/helm-charts/blob/master/charts/prometheus-thanos/values.yaml#L221-L228

**Comment by sshishov** [comment]
@monotek I was saying about this file: https://github.com/kiwigrid/helm-charts/blob/master/charts/prometheus-thanos/README.md

Everyone who is using your chart, looking for documentation and not directly to `values.yaml` file. Only people with experience looking inside. And after looking, you can find a lot of mismatches, which is confusing.

**Comment by monotek** [comment]
PRs with fixes welcome ;-)

**Pull request merged**
