### PR TITLE
[fluentd-elasticsearch] Changed the way services are templatized

### PR DESCRIPTION
**Pull request by etiennejournet**
#### What this PR does / why we need it:
This PR changes the way service are set up in the Chart. 
Until now, you had to define a service for the servicemonitor, but in the case several service ports were needed (e.g syslog forwarder), every svc had to be one of NodePort, ClusterIP or LoadBalancer (you don't necessary want your metrics svc to be a nodePort)
In addition, the servicemonitor would range over the list of svc port, but in the end the Kubernetes object was taking only one "port" selector.

Thats why I feature-flipped the creation of a metrics-svc, using the `serviceMonitor.enabled` boolean, and changed the `service` structure so that you can define several services of any type you want (per service).

#### Which issue this PR fixes
This issue fixes a bug of ranging over the list of service ports and displaying multiple "ports" in the serviceMonitor selector section

#### Special notes for your reviewer:
I'm not sure about the `name: {{ include "fluentd-elasticsearch.fullname" $ | trunc 50 }}-{{ $port.name | trunc 12 }}` in service definition, any idea would be welcome

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://developercertificate.org) signed
- [X] Chart Version bumped (if the pr is an update to an existing chart)
- [X] Variables are documented in the README.md
- [X ] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)

### CODE REVIEW

**Comment by monotek** [comment]
As @zidex implemented this id like to hear his opinion about the change...

**Comment by etiennejournet** [comment]
upgrading tag from 4.2.1 to 4.3.0 is ok for you ?

**Comment by monotek** [comment]
Yes, please also resolve merge conflicts...

**Comment by etiennejournet** [comment]
ship it

**Comment by monotek** [comment]
@etiennejournet 
could you please join discussion in: https://github.com/kiwigrid/helm-charts/pull/141

**Pull request merged**
