### PR TITLE
[fluentd-elasticsearch] Fix bug introduced in #127

### PR DESCRIPTION
**Pull request by chrisob**
@monotek 
#### What this PR does / why we need it:
#127 introduced a bug which breaks any configurations with the following values override:
```
serviceMonitor:
  enabled: true
```

This PR simply re-adds the `serviceMonitor.path: /metrics` default value that was (mistakenly?) removed in  #127.

#### Special notes for your reviewer:
This is the second (or third?) time I've encountered a breaking bug since this chart has moved here from helm/charts. Maybe PR reviews/CI could be a bit more comprehensive?

#### Checklist
- [x] [DCO](https://developercertificate.org) signed
- [x] Chart Version bumped (if the pr is an update to an existing chart)
- [x] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)

### CODE REVIEW

**Comment by monotek** [comment]
@etiennejournet 
can you explain why it was removed inm the first place?

**Comment by chrisob** [comment]
Also the commented-out port in values.yaml](https://github.com/etiennejournet/helm-charts-1/blob/1e9b5286aa0f335af27746aa3d59768236b539fe/charts/fluentd-elasticsearch/values.yaml#L134) doesn't reflect the new service port/type syntax (which BTW, is super non-conventional) :man_facepalming: 

IMHO #127  should have been a [major semver bump](https://semver.org/#spec-item-8) to 5.0.0, as there are non-backwards compatible changes.

**Comment by etiennejournet** [comment]
Hello, 

I agree it should have been a major release.

It was my error removing the `serviceMonitor.path`, sorry. I think the linting shouln't have worked with no default value set.

@chrisob i know it's different from what you can find (on charts/stable repo for example) but how would you have done it ? 
My use case was : you might want to expose a nodeport for enabling tcp/syslog relay through load-balancer but at the same time you don't want to expose your metrics svc as a nodeport because your prometheus is inside your cluster.

**Comment by monotek** [comment]
Side note: The helm repo changed. Maintainers kept the same. So no real difference there...

**Comment by chrisob** [comment]
@monotek OK, I understand. If you're fine with this fix as-is, could you please approve/merge?

**Comment by monotek** [comment]
done :-)

**Pull request merged**
