### PR TITLE
Bump keycloak controller version

### PR DESCRIPTION
**Pull request by oscarfh**
Bump regarding https://github.com/kiwigrid/keycloak-controller/pull/18

### CODE REVIEW

**Comment by axdotl** [comment]
You've to push something to trigger the CI again.

**Comment by oscarfh** [comment]
@monotek can you please retrigger the build? The other PR has been merged and the build should not pass

**Comment by axdotl** [comment]
Please adjust your gitconfig and set an appropriate username and mail address: `Oscar <3311764+oscarfh@users.noreply.github.com>` is not enough, unfortunately.

**Comment by oscarfh** [comment]
Why not? This e-mail is the recommended approach by github. From https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address
"You cannot verify email addresses from disposable domains. If you'd like to keep your email address private, you can use a GitHub-provided noreply email address."

**Comment by oscarfh** [comment]
Now I am little bit confused. Are you talking about the signature or the commit itself?

**Comment by oscarfh** [comment]
I changed the signature, as request @axdotl

**Comment by axdotl** [comment]
> Now I am little bit confused. Are you talking about the signature or the commit itself?

From GitHub point of view you're right. But we're using the DCO (<https://developercertificate.org>) in this project, which requires a real-name and mail-address.

**Pull request merged**
