### PR TITLE
[fluentd-elasticsearch] Change repo

### LINKED ISSUE #113: [stable/fluentd-elasticsearch] Cannot download image
Hello,

I am getting:
`Back-off pulling image "gcr.io/fluentd-elasticsearch/fluentd:v2.5.2"`

also https://console.cloud.google.com/gcr/images/fluentd-elasticsearch/GLOBAL/fluentd seems to not have any public images. 

I was wondering if anyone else was experiencing this?

### PR DESCRIPTION
**Pull request by naseemkullah**
Please see #114 for comments

Fixes #113

### CODE REVIEW

**Comment by monotek** [comment]
We've moved the repo for a reason.
The old one you're using now has only push access by google employees.

We will fixing the new one...

See also: https://github.com/kubernetes/kubernetes/issues/78684

**Comment by naseemkullah** [comment]
Ok

**Comment by naseemkullah** [comment]
I understand but the old one I’m using was the only available one Yesterday.

Consider using an image hosted by fluentd or something more official then your personal repo.

**Comment by naseemkullah** [comment]
For the time being we could have used the old repo as well so the chart would work with default values until issue was fixed. But if you prefer your personal repo then sure that works too.

**Comment by monotek** [comment]
Old repo would mean a downgrade to an older version.
Changing the chart is also not needed as the image & tag are configurable anyway.

**Comment by naseemkullah** [comment]
Working old image was still a better option than non existing new image.
Chart should always have working default valuies imho.

**Comment by monotek** [comment]
config of the current helm chart could not fit to the old image... no time to test that...
anyway... there is an image available you can use, which has the same fluentd / gem versions as v2.5.2.

```
image:
  repository: registry.hub.docker.com/monotek/fluentd-elasticsearch
  tag: 27
```

**Comment by naseemkullah** [comment]
Ok tnx

**Pull request closed without merging**
