### PR TITLE
[prometheus-thanos] - Fix default retentionResolution5m in README.md

### PR DESCRIPTION
**Pull request by joao-dantas**
#### What this PR does / why we need it:

Updates the documentation of a specific property in the README.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://developercertificate.org) signed
- [x] Chart Version bumped (if the pr is an update to an existing chart)
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)

### CODE REVIEW

**Comment by rpahli** [comment]
@joao-dantas thanks for the PR can you pls squash and sign your commits.

**Comment by joao-dantas** [comment]
@rpahli done :)

**Comment by rpahli** [comment]
can you pls also update the chart version. I missed it in my first review.

**Comment by joao-dantas** [comment]
Done, @rpahli

**Review by rpahli — APPROVED** [review]

**Pull request merged**
