### PR TITLE
[graphite] bump apiversion to v2 in order to support helm chart dependencies

### PR DESCRIPTION
**Pull request by JonoNiemann**
#### What this PR does / why we need it:
* Support for apiversion 2, allowing use of dependencies in the chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://developercertificate.org) signed
- [x] Chart Version bumped (if the pr is an update to an existing chart)
- [x] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)

### CODE REVIEW

**Comment by JonoNiemann** [comment]
Signed-off-by: JonoNiemann <zoeyruthniemann@gmail.com>

**Comment by JonoNiemann** [comment]
cc: @monotek

**Comment by JonoNiemann** [comment]
cc: @monotek   @rpahli

**Review by rpahli — APPROVED** [review]

**Comment by JonoNiemann** [comment]
hey @rpahli 

Would you mind taking a look or trying to rerun action... 

the deploy step failed in actions

https://github.com/kiwigrid/helm-charts/actions/runs/5575998523/job/15098440124

**Pull request merged**
